server:
  port: 8080

spring:
  application:
    name: jose
  r2dbc: 
    url: ${DATABASE_URL} 
    #r2dbc:postgresql://ep-dry-feather-a50464ji.us-east-2.aws.neon.tech:5432/jose?sslmode=require
    username: ${DATABASE_USERNAME}
    #JG-ChatBot_owner
    password: ${DATABASE_PASSWORD}
    #Qbr4YsUfdz6R
  contentmoderator: 
    apikey: ${API_KEY} 
    #ba8653abc2mshd8ced1fcbfe3b6dp1ac8e6jsn2f87dde7ca7b

